import Nav from "@/components/Header/Nav";
import "../styles/globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
